name: Coolify - Application Deploy

on:
  push:
    branches: [ main ]
  # or whatever trigger you need

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: marconneves/coolify-action@v0.0.4
        # your step configuration here
